name: Blob storage website CI

env:
  storageName: 'storage12345webhost'
  resourceGroupName: 'Resources'
  cdnProfileName: 'staticwebsitecdn'
  cdnEndpointName: 'staticwebsitecdnendpoint'

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.x', '14.x' ]
    name: Build Node version ${{ matrix.node }}
    steps:            
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ' ${{ matrix.node }}'
    - run: |
        cd $GITHUB_WORKSPACE/incidents-app
        npm install
        npm run build

  deploy:
    runs-on: ubuntu-latest
     steps:
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.storageName }} -s $GITHUB_WORKSPACE/incidents-app/build  -d '$web'
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name ${{ env.cdnProfileName }} --name ${{ env.cdnEndpointName }}  --resource-group ${{ env.resourceGroupName }}

    - name: Logout
      run: |
            az logout