name: Static website Azure Storage CI/CD

env:
  storageName: 'storage12345webhost'
  resourceGroupName: 'Resources'
  cdnProfileName: 'staticwebsitecdn'
  cdnEndpointName: 'staticwebsitecdnendpoint'
  artifactName: 'build-results-artifact'

on:
    push:
        branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: |
        cd ${{ github.workspace }}/incidents-app
        npm install
        npm run build
        
    - uses: actions/upload-artifact@master
      with:
        name:  ${{ env.artifactName }}
        path: ${{ github.workspace }}/incidents-app/build

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - run: mkdir build
    - uses: actions/download-artifact@master
      with:
        name: ${{ env.artifactName }}
        path:  build

    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.storageName }} -s   -d '$web'

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name ${{ env.cdnProfileName }} --name ${{ env.cdnEndpointName }}  --resource-group ${{ env.resourceGroupName }}
          
    - name: logout
      run: |
            az logout